### PR TITLE
[FIX] pos_customer_wallet[_*]: Rename foodprint class

### PR DESCRIPTION
**Pull request by carmenbianca**
Signed-off-by: Carmen Bianca Bakker <carmen@coopiteasy.be>

## Description

The class name was wrongly copied from some other place and does not reflect what it's trying to represent.

## Odoo task (if applicable)

Reported by @polchampion [here](https://github.com/coopiteasy/addons/commit/175d699a355b627339e0b31bb2df9e723dbb32d8)

Deploy task: https://gestion.coopiteasy.be/web?debug=1#id=10848&action=475&active_id=264&model=project.task&view_type=form&menu_id=536

## Checklist before approval

- [x] Tests are present (or not needed).
- [x] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

### CODE REVIEW

**Review by polchampion — COMMENTED** [review]
@carmenbianca perfect, thanks

**Review by legalsylvain — APPROVED** [review]
makes senses. Thanks.

**Comment by legalsylvain** [comment]
should be rebased and merged ?

**Comment by legalsylvain** [comment]
> Hi https://github.com/coopiteasy,
> some modules you are maintaining are being modified, check this out!

Hi. I think that the maintainer is not the good one. coop it easy can be set in the author keys, for statistics purpose. But regarding the maintainers, should be "real" people. maintainers give write access to fix / migrate modules. (important if the module moves under OCA umbrella)

**Review by legalsylvain — APPROVED** [review]

**Comment by carmenbianca** [comment]
Thank you @legalsylvain for the review!

**Pull request merged**
