### PR TITLE
[ADD] add new module website_rebrand_coopiteasy

### PR DESCRIPTION
**Pull request by huguesdk**
## description

add a new module to replace the default odoo website branding by a coop it easy branding.

## odoo task

[t12258](https://gestion.coopiteasy.be/web#id=12249&model=project.task)

### CODE REVIEW

**Review by victor-champonnois — COMMENTED** [review]
More a comment than a review : "Odoo by Coop IT Easy" sounds like Odoo is a product from Coop IT Easy. I would be more precise, for instance "Odoo, supplied by Coop IT Easy".

**Comment by huguesdk** [comment]
indeed. i had the same impression, and your suggestion sounds very good and accurate. other options i think of would be “provided by” or “managed by”.

**Review by remytms — APPROVED** [review]
LGTM

**Pull request merged**
