### PR TITLE
[FIX] website_sale_product_display_unit: Adjust templates to low priority

### PR DESCRIPTION
**Pull request by carmenbianca**
## Odoo task (if applicable)

https://gestion.coopiteasy.be/web#id=9377&action=479&model=project.task&view_type=form&menu_id=536

## Checklist before approval

- [ ] Tests are present (or not needed).
- [ ] Credits/copyright have been changed correctly.
- [ ] Change log snippet is present.
- [ ] (If a new module) Moving this to OCA has been considered.

### CODE REVIEW

**Review by victor-champonnois — APPROVED** [review]
LGTM

**Comment by carmenbianca** [comment]
/ocabot merge patch

thank you @victor-champonnois

**Comment by carmenbianca** [comment]
thank goodness

**Pull request merged**
