### PR TITLE
12.0 add website recaptcha

### PR DESCRIPTION
**Pull request by victor-champonnois**
[related issue ](https://github.com/coopiteasy/vertical-cooperative/issues/221)
[related PR in vertical-cooperative](https://github.com/coopiteasy/vertical-cooperative/pull/231)
[related PR in Obeesdoo](https://github.com/beescoop/Obeesdoo/pull/313)

### CODE REVIEW

**Review by robinkeunen — APPROVED** [review]
LGTM

**Review by carmenbianca — CHANGES_REQUESTED** [review]
The Git history of the module is not preserved in this PR. Unless that's not at all important, I wouldn't merge like this.

**Comment by victor-champonnois** [comment]
> The Git history of the module is not preserved in this PR. Unless that's not at all important, I wouldn't merge like this.

- Don't know if it's important... @robinkeunen what do you think ?

- If it is, how would I preserve the git history of the module ?

**Comment by carmenbianca** [comment]
There are two ways that are documented within CIE.

The difficult way: https://gitlab.com/coopiteasy/doc/-/blob/master/documentation/move-a-module.md

The easier way: https://gitlab.com/coopiteasy/infra/-/blob/master/tools/cie_move_module.sh

I prefer doing the easier way manually, though, for which I noted down personal instructions:

```shell
git format-patch --keep-subject --stdout "$(git rev-list --max-parents=0 HEAD)" -- $MODULE_NAME_HERE > /tmp/out.patch
# `git rm` the module
# `cd` to the new repository
# `git switch` to a new branch
git am -3 --keep /tmp/out.patch
```

Note: The easier way may be impossible if there's too much complicated git history magic going on in the module.

**Comment by victor-champonnois** [comment]
ahah, didn't know about this documentation, thx !

**Comment by robinkeunen** [comment]
Just like Carmen says ☝️

**Pull request closed without merging**
