### PR TITLE
Remove account_invoice_reminder from 9.0 branch

### PR DESCRIPTION
**Pull request by carmenbianca**
Possibly to be merged after #195 is merged.

### CODE REVIEW

**Review by robinkeunen — CHANGES_REQUESTED** [review]
You need not remove this module from branch 9.0 when doing a migration, you're just making it available in another version.

**Comment by carmenbianca** [comment]
Ah, [this line in our migrate script](https://gitlab.com/coopiteasy/infra/-/blob/master/tools/cie_move_module.sh#L59) gave me a different impression.

**Comment by robinkeunen** [comment]
This script moves a module from a repository to another. What you're doing is migrating from one version/branch to another version/branch within the same repository.

If not clear, I can explain on framatalk.

**Comment by carmenbianca** [comment]
Super clear, thank you!

**Pull request closed without merging**
