### PR TITLE
Add sale_report_carrier module

### PR DESCRIPTION
**Pull request by carmenbianca**
Task: https://gestion.coopiteasy.be/web#id=7023&view_type=form&model=project.task

For some reason the translations don't work for this module.

### CODE REVIEW

**Comment by robinkeunen** [comment]
This is closely related to https://github.com/coopiteasy/lefournil-custom/pull/1 from @coccinouille . It even solves part of his problem. You should make sure both you PR are compatible.

**Review by robinkeunen — APPROVED** [review]
This is closely related to https://github.com/coopiteasy/lefournil-custom/pull/1 from @coccinouille . It even solves part of his problem. You should make sure both you PR are compatible.

Otherwise, very good work.

**Comment by carmenbianca** [comment]
@robinkeunen I believe that there is no code conflict here. `le_fournil_du_loup` inherits the sale report for `report.all.channels.sales`, and this PR inherits `sale.report`.

There may be a conflict on use cases, though, but I find that difficult to assess.

**Comment by robinkeunen** [comment]
> @robinkeunen I believe that there is no code conflict here. `le_fournil_du_loup` inherits the sale report for `report.all.channels.sales`, and this PR inherits `sale.report`.
> 
> There may be a conflict on use cases, though, but I find that difficult to assess.

It looked very similar, thanks for checking 🙌

**Pull request merged**
